---
- name: Configure Linux VM
  hosts: azure_vms
  become: true
  tasks:
    - name: Ensure NGINX is installed
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and enable NGINX
      systemd:
        name: nginx
        state: started
        enabled: true

    - name: Create a welcome index.html
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Hello from Ansible on Azure VM</h1>"

