---
- name: Configure RHEL Azure VM and Install NGINX
  hosts: linux_servers
  become: true

  tasks:
    - name: Install required base packages
      yum:
        name: ['git', 'curl', 'wget']
        state: present

    - name: Enable and start firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Allow HTTP service through firewalld
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: Ensure EPEL repository is available
      yum:
        name: epel-release
        state: present

    - name: Install NGINX
      yum:
        name: nginx
        state: present

    - name: Enable and start NGINX service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Display NGINX status
      command: systemctl status nginx
      register: nginx_status
      ignore_errors: true

    - name: Show NGINX status output
      debug:
        var: nginx_status.stdout_lines

